### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by Strongleong** [tjdevries/vim9jit#28]
When I run `cargo build` I get this error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> crates/vim9-lexer/src/lib.rs:1:1
  |
1 | #![feature(let_chains)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `vim9-lexer` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by Strongleong** [comment]
Found solution. Feature `let_chains` is available in rust nightly. But I am not closing this issue because I think code should compile with stable rust or need in nightly rust must be specified in readme

**Comment by tjdevries** [comment]
Thanks! I also moved the version to 1.72.0 for the toolchain, so that should all work now without nightly
